version: '3.9'
services:
    db:
        networks:
            - app
        image: 'postgres:16.0'
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: supersecure
            POSTGRES_USER: moab
            POSTGRES_DB: rinhadb
        volumes:
            - 'rinhadb:/var/lib/postgresql/data'
            - './db.sql:/docker-entrypoint-initdb.d/init.sql'

networks:
    app:

volumes:
    rinhadb:
